# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f41c838857b50f53f799d04a8ecbd670c258af4aa4a5a7022a10c5c2925b6cd53f580f86954cefaa241f3239a1e206dd1c55b8d61a25c0d6d96a2fd17dcf07

test:
  secret_key_base: bc3251b225f41a57764cfd75525ff7c7ea3f746c56f1a7e9e852f8c98ed8da3ac5301cd0e8e2dc2cc0d46d418d1f0617ccf67699d9957a1663f0c47d40dfa6dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
