smtp:
<<<<<<< HEAD
  hostname:
  username:
  password:
  from: 'noreply@example.com'

domain: 'localhost'

slack:
  app_id: ''
  app_secret: ''
=======
  hostname: smtp.example.com
  username: postmaster@example.com
  password: 12345678

slack:
  app_id:
  app_secret:
>>>>>>> 215cd829c1fc2cad0672daaaac02c8e96e7c0373
